language: node_js
  - "10"

branches:
  only:
    - master

before_script:
  - yarn install

script:
  - node track/TrackChanges.js

after_success:
  - |
    if [[ "false" != "$TRAVIS_PULL_REQUEST" ]]; then
      echo "Not deploying pull requests."
      exit
    fi
  - |
    if [[ "master" != "$TRAVIS_BRANCH" ]]; then
    	echo "Not on the 'master' branch."
    	exit
    fi
  - git clone "https://github.com/${TRAVIS_REPO_SLUG}.git" en
  - cd en
  - git checkout en
  - cp ../required-en.md ./
  - mv required-en.md required.md
  - git config user.name "mirucon"
  - git config user.email "i@miruc.co"
  - git add required.md
  - git commit -m "Original change detected"
  - git push -f "https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git" en
